// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirx1TyK_zMzGJQP-WwsxfHXjBQ7JNrVc',
    appId: '1:947507657909:web:dfa8f3589bad5ea4af92fc',
    messagingSenderId: '947507657909',
    projectId: 'chat-app-13d90',
    authDomain: 'chat-app-13d90.firebaseapp.com',
    storageBucket: 'chat-app-13d90.appspot.com',
    measurementId: 'G-HDBCCN0ZZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuK31i6f8HeyprwYjc3LIvaYSzicRyMKs',
    appId: '1:947507657909:android:c5079e6cfb33d4bdaf92fc',
    messagingSenderId: '947507657909',
    projectId: 'chat-app-13d90',
    storageBucket: 'chat-app-13d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJBgRaLG5TptD6AaBxjwVPOLbiZPi1Nk',
    appId: '1:947507657909:ios:b97e03c2c16df33aaf92fc',
    messagingSenderId: '947507657909',
    projectId: 'chat-app-13d90',
    storageBucket: 'chat-app-13d90.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJBgRaLG5TptD6AaBxjwVPOLbiZPi1Nk',
    appId: '1:947507657909:ios:b2d589abcaa448e4af92fc',
    messagingSenderId: '947507657909',
    projectId: 'chat-app-13d90',
    storageBucket: 'chat-app-13d90.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
